### ISSUE TITLE
Verwijderen planning.

### ISSUE THREAD

**Issue by Tjoosten** [Scouts-Sint-Joris/SIJOT-1.x#4]
Na de vergadering van het ouder comité gisteren is besloten om de planning van de website te halen. 
Wegens interne redenen. (REF: Verslag OC 3/11/2016) In mijn mailbox). 

## TODO: 
- [x] Aanpassen lokaal
- [x] Pushen in seperate branch naar git. 
- [x] Uploaden naar server (SFTP). 
- [x] Mailen naar vzw voor de aanpassing
