### ISSUE TITLE
Nieuwe foto's voor de verhuur

### ISSUE THREAD

**Issue by Tjoosten** [Scouts-Sint-Joris/SIJOT-1.x#7]
Recent zijn er ook renovatie werken gedaan aan de gebouwen. Hierom moeten ook nieuwe foto's van het domein genomen worden. Om vervolgens te wijzigen op de website. (REF: Puntje van het OC). 

#### TODO: 

- [ ] Fotos gaan nemen op het domein. 
- [ ] Foto's bewerken en optimalizeren voor een website. 
- [ ] Lokaal de website aanpassen. 
- [ ] Pushen in seperated branch naar github. 
- [ ] Uploaden naar server (SFTP). 
- [ ] Mailen naar vzw omtrent wijziging van de website.
