### ISSUE TITLE
Toevoegen informatie BHK

### ISSUE THREAD

**Issue by Tjoosten** [Scouts-Sint-Joris/SIJOT-1.x#8]
### TODO: 
 
- [ ] Toevoegen: BHK info. 
- [ ] Toevoegen: Programma van BHK. 
  - [ ] *Zaterdag namiddag:* Wandelzoektocht familie. 
  - [ ] *Zaterdag avond:* Kaartavond voor de liefhebbers. 
  - [ ] *Zondag middag:* Familie restaurant en een gezellig samen zijn. 
  - [ ] *Zondag namiddag:* Optredens -> LLP, Dansgroep de gilden....    
- [x] Toevoegen: inschrijvings formulier kaartavond.

**Comment by Tjoosten** [comment]
Not relavant
